### ISSUE TITLE
'str' object has no attribute 'sign_in_with_email_and_password'

### ISSUE THREAD

**Issue by gabrielemaffoni** [nhorvath/Pyrebase4#1]
Hi!
I'm trying to login to existing user accounts. I am sure everything is setup correctly (python 3.5, Auth Sign In enabled in my Firebase). However, I keep having the same problem over and over: 'str' object has no attribute 'sign_in_with_email_and_password(email, password)'.

here's the code:
```python
def sign_in():
    global auth
    global user
    email = input("Please, enter your email")
    password = input("Please, enter your password")
    user = auth.sign_in_with_email_and_password(email, password)
    get_user_id(user)
```

I can't seem to find a solution.
Any help?!

**Comment by nhorvath** [comment]
auth is not merely a global variable it's a reference to the firebase authentication object. You should read the readme of this project.

```python
import pyrebase

config = {
  "apiKey": "apiKey",
  "authDomain": "projectId.firebaseapp.com",
  "databaseURL": "https://databaseName.firebaseio.com",
  "storageBucket": "projectId.appspot.com"
}

firebase = pyrebase.initialize_app(config)

# Get a reference to the auth service
auth = firebase.auth()
```
