### ISSUE TITLE
Support: Does pyrebase4 has the ability to store a base64 encoded image to firebase?

### ISSUE THREAD

**Issue by kengoon** [nhorvath/Pyrebase4#17]
I belive that firebase has the ability to store base64 encoded image, I don't know if the feature is included in this library or not. it will be really nice to have it

**Comment by nhorvath** [comment]
If you base64 encode it it's a string so yes.

**Comment by kengoon** [comment]
@nhorvath please can you show an example?  please

**Comment by nhorvath** [comment]
https://www.google.com/search?q=base64+encode+image+python&oq=base64+encode+image+python&aqs=chrome..69i57j69i60l2.5170j0j4&sourceid=chrome&ie=UTF-8

**Comment by kengoon** [comment]
I meant you should show an example of how to store the base64 image string in firebase

**Comment by nhorvath** [comment]
It's just a string. Read the readme.

**Comment by kengoon** [comment]
ok

**Comment by kengoon** [comment]
@nhorvath I get this error `ValueError: total bytes could not be determined. Please pass an explicit size, or supply a chunk size for a streaming transfer.` when I try to upload an image to firebase

**Comment by kengoon** [comment]
i checked the library and discovered that there is no parameter for chunk_size
