### ISSUE TITLE
Requirement is pinned for Pyrebase4 4.4.1: oauth2client==4.1.2

### ISSUE THREAD

**Issue by MartinHjelmare** [nhorvath/Pyrebase4#20]
# Description
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

```
(home-assistant) x$ pip install -r requirements_all.txt
...
(home-assistant) x$ pipdeptree -w silence -r -p oauth2client
oauth2client==4.0.0
...
  - gcloud==0.18.3 [requires: oauth2client>=2.0.1]
    - Pyrebase4==4.4.1 [requires: gcloud==0.18.3]
      - thermoworks-smoke==0.1.8 [requires: pyrebase4>=4.3.0]
  - Pyrebase4==4.4.1 [requires: oauth2client==4.1.2]
    - thermoworks-smoke==0.1.8 [requires: pyrebase4>=4.3.0]
```

Make sure these boxes are checked before submitting your issue:

- [x] Check that your version of Python is 3.4+
- [x] Check that you are on the newest version of Pyrebase
- [ ] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.

Please don't be discouraged if you do not get a response to your issue quickly,
I maintain Pyrebase for fun and don't always have as much free time as I'd like.

Thank you for helping make Pyrebase better!

**Comment by nhorvath** [comment]
ok i'll change it to >= I just hope a future version won't break this project.

**Comment by MartinHjelmare** [comment]
The `oauth2client` library is deprecated so the risk for new versions that break compatibility is low.

**Comment by MartinHjelmare** [comment]
I see there's a new release. Thanks for the help! :heart:
