### ISSUE TITLE
Another Authentication Method

### ISSUE THREAD

**Issue by moepoi** [nhorvath/Pyrebase4#5]
Make sure these boxes are checked before submitting your issue:

[x] Check that your version of Python is 3.4+
[x] Check that you are on the newest version of Pyrebase
[x] Check that Email/password provider is enabled in your Firebase dashboard under Auth -> Sign In Method.

Please don't be discouraged if you do not get a response to your issue quickly,
I maintain Pyrebase for fun and don't always have as much free time as I'd like.

Thank you for helping make Pyrebase better!

Hello, I'm using pyrebase for my website to handle authentication but it can only sign in using email and password. Can pyrebase support using phone auth or another oauth like twitter or github auth ?

**Comment by nhorvath** [comment]
Only email authentication is supported. Feel free to submit a pull request.
