### ISSUE TITLE
Firebase Storage - Download Path

### ISSUE THREAD

**Issue by arncode90** [nhorvath/Pyrebase4#53]
Make sure these boxes are checked before submitting your issue:

`storage.child(#firebse-file-path-location).download(filename='#local-path-location', path='#?')`

What is "path" do/refer to in download method?

Thank you for helping make Pyrebase better!

**Comment by nhorvath** [comment]
the download method is `download(path="/save/path", filename="save-file.ext")` filename should not contain path components.

**Comment by AsifArmanRahman** [comment]
> the download method is `download(path="/save/path", filename="save-file.ext")` filename should not contain path components.

Sorry to inform you that your explanation is incorrect. `path` parameter is actually used as `firebase-file-path-location` only when using it with service credentials, otherwise it is a parameter that is not used.
