### ISSUE TITLE
download() missing 1 required positional argument: 'filename'

### ISSUE THREAD

**Issue by woscar01** [nhorvath/Pyrebase4#7]

**Comment by nhorvath** [comment]
Looks like the documentation for download is wrong. It should be download(path, filename)

**Comment by jayednahain** [comment]
> Looks like the documentation for download is wrong. It should be download(path, filename)

thank you so much!

**Comment by BLACK-CAT13** [comment]
may i ask how is the code for it?

**Comment by dark-matter08** [comment]
> Looks like the documentation for download is wrong. It should be download(path, filename)

I realised this while working with pyrebase4 but when i used it, it cleared the error i was having but my image did not download

**Comment by golebu2020** [comment]
storage.child("profile_pictures/example.jpg").download(path="gs://poster-#####spot.com/", filename="downloaded.jpg")

That will solve the problem
