### ISSUE TITLE
requests 2.31.0 suppport.  Is this repo still being maintained?

### ISSUE THREAD

**Issue by kbirger** [nhorvath/Pyrebase4#77]
This package relies on an outdated version of requests, which is causing conflicts. It would be nice to upgrade to requests 2.31.0.

I found a fork that implements this a few days ago: https://github.com/somechazzy/Pyrebase4

There's no way to reach out, so I don't know if the author intends to submit a PR here or not. But I'm using those changes right now, and they are working great, so it could be ported back to this repo I think

**Comment by nhorvath** [comment]
Merging stuff today that fixes this.

**Comment by nhorvath** [comment]
release 4.8.0 created https://pypi.org/manage/project/Pyrebase4/release/4.8.0/
