### ISSUE TITLE
Package installed but import fails.

### ISSUE THREAD

**Issue by glebgrig0** [nhorvath/Pyrebase4#8]
I am trying to use this package but unfortunately when I run my code it just says that the module is not found, even thought pip says that the install requirment is already satisfied. I 've tried it on two Windows systems with a fresh install of Python. 
(No I don't have any other versions of python installed)
please help.

**Comment by HarsheetKakar** [comment]
try it with a virtualenv maybe. If it doesn't work just paste a picture of what the error is.

**Comment by harvitronix** [comment]
@glebgrig0 I had to uninstall Pyrebase first, then install this version, then the import worked (`import pyrebase` not `import pyrebase4`).
